//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Pessoa = new HashSet<Pessoa>();
            this.Venda = new HashSet<Venda>();
        }
    
        public int cli_id { get; set; }
        public string cli_email { get; set; }
    
        public virtual ICollection<Pessoa> Pessoa { get; set; }
        public virtual ICollection<Venda> Venda { get; set; }
    }
}
