//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filme
    {
        public Filme()
        {
            this.Ingressos = new HashSet<Ingressos>();
        }
    
        public int fil_id { get; set; }
        public string fil_titulo { get; set; }
        public Nullable<System.DateTime> fil_datalan { get; set; }
        public Nullable<int> fil_idademin { get; set; }
        public int gen_id { get; set; }
        public string fil_tipo { get; set; }
        public string fil_descricao { get; set; }
        public System.DateTime fil_tempo { get; set; }
    
        public virtual Genero Genero { get; set; }
        public virtual ICollection<Ingressos> Ingressos { get; set; }
    }
}
