//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genero
    {
        public Genero()
        {
            this.Filme = new HashSet<Filme>();
        }
    
        public int gen_id { get; set; }
        public string gen_filme { get; set; }
    
        public virtual ICollection<Filme> Filme { get; set; }
    }
}
