//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItensVenda
    {
        public int itv_id { get; set; }
        public int ven_id { get; set; }
        public int itv_qtd { get; set; }
    
        public virtual Venda Venda { get; set; }
    }
}
