//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposIngresso
    {
        public TiposIngresso()
        {
            this.Ingressos = new HashSet<Ingressos>();
        }
    
        public int tin_id { get; set; }
        public string tin_tipo { get; set; }
        public string tin_descricao { get; set; }
    
        public virtual ICollection<Ingressos> Ingressos { get; set; }
    }
}
