//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        public Venda()
        {
            this.ItensVenda = new HashSet<ItensVenda>();
        }
    
        public int ven_id { get; set; }
        public Nullable<System.DateTime> ven_datahora { get; set; }
        public int fun_id { get; set; }
        public int cli_id { get; set; }
        public int ing_id { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Funcionario Funcionario { get; set; }
        public virtual Ingressos Ingressos { get; set; }
        public virtual ICollection<ItensVenda> ItensVenda { get; set; }
    }
}
